using Microsoft.CodeAnalysis;
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using AssetGen.DataStructures;
using AssetGen.Utils;
using AssetGen.Core.Generators;

namespace AssetGen.Core;

[Generator(LanguageNames.CSharp)]
internal sealed class Generation : IIncrementalGenerator
{
    private const string BuildManifestFileName = "build.txt";

    private static readonly AssetGenerator[] Generators =
        [
            new EffectGenerator(),
            new ObjModelGenerator(),
            new Texture2DGenerator(),
        ];

    public const string AssetNamespace = "GeneratedAssets";

    public const string Header = $$$"""
// <auto-generated/>

#pragma warning disable
""";

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyName = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName!);

        // Common files.
        context.RegisterSourceOutput(assemblyName, static (context, assemblyName) =>
        {
            context.AddSource(GenerateLazyAsset(assemblyName));

            context.AddSource(GenerateAssetReloader(assemblyName));
            context.AddSource(GenerateLocalAssetSource(assemblyName));
        });

        // Search for the build manifest (build.txt) file to get the mod's root directory.
        var projectRoot = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(BuildManifestFileName))
            .Collect()
            .Select(static (files, _) =>
                Path.GetDirectoryName(files[0].Path)!
                    .Replace('\\', '/'));

        foreach (AssetGenerator generator in Generators)
        {
            var texts = context.AdditionalTextsProvider
                .Where(p =>
                    generator.FileExtensions.Any(ext => p.Path.EndsWith($".{ext}", StringComparison.OrdinalIgnoreCase)));

            var assets = texts
                .Combine(projectRoot)
                .Select((tuple, _) =>
                    new AssetFile(tuple.Left, tuple.Right))
                .Collect();

            IncrementalValueProvider<(
                ImmutableArray<AssetFile> Assets,
                string AssemblyName)> 
                tuple = assets.Combine(assemblyName);

            context.RegisterSourceOutput(tuple, (context, tuple) =>
                generator.AddSource(context, tuple.Assets, tuple.AssemblyName));
        }
    }

    #region Common

    private static GeneratedFile GenerateLazyAsset(string assemblyName)
    {
        StringBuilder writer = new();

        writer.AppendLine(Header);

        writer.AppendLine($$$"""
using ReLogic.Content;

using System;

using Terraria.ModLoader;

namespace {{{assemblyName}}}.{{{AssetNamespace}}}.DataStructures;

/// <inheritdoc cref="Asset{T}"/>
[System.Runtime.CompilerServices.CompilerGenerated]
internal readonly record struct LazyAsset<T> where T : class
{
    private readonly Lazy<Asset<T>> _asset;

    private readonly string _key;

    public readonly Asset<T> Asset => _asset.Value;

    /// <inheritdoc cref="Asset{T}.Value"/>
    public readonly T Value => Asset.Value;

    public readonly bool IsReady => 
        Asset is not null && 
        Value is not null && 
        Asset.IsLoaded &&
        !Asset.IsDisposed;

    public readonly string Key => _key;

    /// <inheritdoc cref="ModContent.Request{T}"/>
    public LazyAsset(string name)
    {
        _key = name;
        _asset = new Lazy<Asset<T>>(() => ModContent.Request<T>(name));
    }

    public void Wait()
    {
        Asset.Wait();
    }

    public static implicit operator Asset<T>(LazyAsset<T> asset)
    {
        return asset.Asset;
    }

    public static implicit operator T(LazyAsset<T> asset)
    {
        return asset.Value;
    }
}
""");

        return new("DataStructures/LazyAsset.g.cs", writer.ToString());
    }

    private static GeneratedFile GenerateAssetReloader(string assemblyName)
    {
        StringBuilder writer = new();

        writer.AppendLine(Header);

        writer.AppendLine($$$"""
using ReLogic.Content;
using ReLogic.Utilities;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Terraria;

using Terraria.ModLoader;

namespace {{{assemblyName}}}.{{{AssetNamespace}}}.Debug;

#nullable enable

#if DEBUG

[Autoload(Side = ModSide.Client)]
[System.Runtime.CompilerServices.CompilerGenerated]
internal sealed class AssetReloader : ModSystem
{
    private static FieldInfo? AssetsInfo;

    private static FieldInfo? RequestLockInfo;

    private static MethodInfo? ForceReloadAssetInfo;

    private const NotifyFilters AllFilters =
        NotifyFilters.FileName |
        NotifyFilters.DirectoryName |
        NotifyFilters.Attributes |
        NotifyFilters.Size |
        NotifyFilters.LastWrite |
        NotifyFilters.LastAccess |
        NotifyFilters.CreationTime |
        NotifyFilters.Security;

    private static FileSystemWatcher? AssetWatcher;

    private static string ModSource = string.Empty;

    private static LocalAssetSource? AssetSource;

    public override void PostSetupContent()
    {
        try
        {
            AssetsInfo = typeof(AssetRepository).GetField("_assets", BindingFlags.NonPublic | BindingFlags.Instance);

            RequestLockInfo = typeof(AssetRepository).GetField("_requestLock", BindingFlags.NonPublic | BindingFlags.Instance);

            MethodInfo[] repositoryMethods = typeof(AssetRepository).GetMethods(BindingFlags.NonPublic | BindingFlags.Instance);
            ForceReloadAssetInfo = repositoryMethods.Single(m => m.Name == "ForceReloadAsset" && !m.IsGenericMethod);

            ModSource = Mod.SourceFolder.Replace('\\', '/');

            if (!Directory.Exists(ModSource))
            {
                throw new DirectoryNotFoundException("Mod source directory does not exsist; this warning should not be present for mod consumers!");
            }

            AssetSource = new LocalAssetSource(ModSource);

            ChangeContentSource(ModSource);

            AssetReaderCollection assetReaderCollection = Main.instance.Services.Get<AssetReaderCollection>();

            string[] extensions = assetReaderCollection.GetSupportedExtensions();

            AssetWatcher = new(ModSource);

            foreach (string e in extensions)
            {
                AssetWatcher.Filters.Add($""*{{e}}"");
            }

            AssetWatcher.Changed += AssetChanged;

            AssetWatcher.NotifyFilter = AllFilters;

            AssetWatcher.IncludeSubdirectories = true;
            AssetWatcher.EnableRaisingEvents = true;
        }
        catch (Exception e)
        {
            Mod.Logger.Warn($""Unable to load Asset Reloader! - {e}"");
        }
    }

    public override void Unload()
    {
        if (AssetWatcher is not null)
        {
            AssetWatcher.EnableRaisingEvents = false;
            AssetWatcher.Dispose();
        }
    }

    private void AssetChanged(object sender, FileSystemEventArgs e)
    {
        if (e.ChangeType.HasFlag(Created))
        {
            return;
        }

        string assetPath = Path.GetRelativePath(ModSource, e.FullPath).Replace('/', '\\');
        
        AssetSource?.AddAssetPath(assetPath);

        assetPath = Path.ChangeExtension(assetPath, null);

        if (e.ChangeType.HasFlag(WatcherChangeTypes.Deleted) ||
            e.ChangeType.HasFlag(WatcherChangeTypes.Renamed))
        {
            Mod.Logger.Warn($"Asset at {assetPath} was removed or renamed!");

            return;
        }

        Dictionary<string, IAsset>? repositoryAssets = (Dictionary<string, IAsset>?)AssetsInfo?.GetValue(Mod.Assets);

        if (repositoryAssets is null)
        {
            throw new NullReferenceException("'Mod.Assets._assets' was null!");
        }

        if (!repositoryAssets.TryGetValue(assetPath, out IAsset? asset) ||
            asset is null)
        {
            return;
        }

        Main.QueueMainThreadAction(() => ReloadAsset(asset));
    }

    private void ReloadAsset(IAsset asset)
    {
        if (RequestLockInfo is null ||
            ForceReloadAssetInfo is null)
        {
            throw new NullReferenceException("Could not force reload asset!");
        }

        lock (RequestLockInfo.GetValue(Mod.Assets))
        {
            ForceReloadAssetInfo.Invoke(Mod.Assets, [asset, AssetRequestMode.ImmediateLoad]);
        }

        InvokeAssetWait(asset);
    }

    private static void InvokeAssetWait(IAsset asset)
    {
        Type type = asset.GetType();

        if (!type.IsGenericType ||
            type.GetGenericTypeDefinition() != typeof(Asset<>))
        {
            throw new ArgumentException($"IAsset was not of type {nameof(Asset<>)}!");
        }

        MethodInfo? getAssetWait = type.GetProperty(nameof(Asset<>.Wait), Public | Instance)?.GetGetMethod();

        Action wait = (Action?)getAssetWait?.Invoke(asset, []) ??
            throw new NullReferenceException($"Asset wait function was null!");

        wait();
    }

    private void ChangeContentSource(string modSource)
    {
        Main.QueueMainThreadAction(() => Mod.Assets.SetSources([AssetSource, Mod.RootContentSource]));
    }
}

#endif
""");

        return new("Debug/AssetReloader.g.cs", writer.ToString());
    }

    private static GeneratedFile GenerateLocalAssetSource(string assemblyName)
    {
        StringBuilder writer = new();

        writer.AppendLine(Header);

        writer.AppendLine($$$"""
using ReLogic.Content;
using ReLogic.Content.Sources;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using Terraria.Initializers;

using static System.Reflection.BindingFlags;

namespace {{{assemblyName}}}.{{{AssetNamespace}}}.Debug;

#if DEBUG

[System.Runtime.CompilerServices.CompilerGenerated]
internal sealed class LocalAssetSource : ContentSource
{
    private string ModSource { get; init; }

    public string[] AssetPaths
	{
		get => assetPaths;
		set => SetAssetNames(value);
	}

    public LocalAssetSource(string modSource) : base()
    {
        ModSource = modSource;

        assetPaths = Array.Empty<string>();
    }

    public override Stream OpenStream(string fullAssetName)
    {
        return File.OpenRead(Path.Combine(ModSource, fullAssetName));
    }

    public void AddAssetPath(string path)
    {
        AssetPaths = AssetPaths.Append(path).ToArray();
    }
}

#endif
""");

        return new("Debug/LocalAssetSource.g.cs", writer.ToString());
    }

    #endregion
}
