using Microsoft.CodeAnalysis;
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using AssetGen.DataStructures;
using AssetGen.Utils;
using AssetGen.Core.Generators;

namespace AssetGen.Core;

[Generator(LanguageNames.CSharp)]
internal sealed class Generation : IIncrementalGenerator
{
    private const string build_manifest_name = "build.txt";

    private static readonly AssetGenerator[] generators =
        [
            new EffectGenerator(),
            new ObjModelGenerator(),
            new Texture2DGenerator(),
        ];

    public const string ASSET_NAMESPACE = "GeneratedAssets";

    public const string HEADER = $$$"""
// <auto-generated/>

#pragma warning disable

""";

    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyName = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName!);

        // Common files.
        context.RegisterSourceOutput(assemblyName,
            static (context, assemblyName) =>
            {
                context.AddSource(GenerateLazyAsset(assemblyName));
            }
        );

        // Search for the build manifest (build.txt) file to get the mod's root directory.
        var projectRoot = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(build_manifest_name))
            .Collect()
            .Select(static (files, _) =>
                Path.GetDirectoryName(files[0].Path)!
                    .Replace('\\', '/'));

        foreach (AssetGenerator generator in generators)
        {
            var texts = context.AdditionalTextsProvider
                .Where(p =>
                    generator.FileExtensions.Any(ext => p.Path.EndsWith($".{ext}", StringComparison.OrdinalIgnoreCase)));

            var assets = texts
                .Combine(projectRoot)
                .Select((tuple, _) =>
                    new AssetFile(tuple.Left, tuple.Right))
                .Collect();

            IncrementalValueProvider<(
                ImmutableArray<AssetFile> Assets,
                string AssemblyName)>
                tuple = assets.Combine(assemblyName);

            context.RegisterSourceOutput(tuple,
                (context, tuple) =>
                {
                    generator.AddSource(context, tuple.Assets, tuple.AssemblyName);
                }
            );
        }
    }

    #region Common

    private static GeneratedFile GenerateLazyAsset(string assemblyName)
    {
        StringBuilder writer = new();

        writer.AppendLine(HEADER);

        writer.AppendLine($$$"""
using ReLogic.Content;

using System;

using Terraria.ModLoader;

namespace {{{assemblyName}}}.{{{ASSET_NAMESPACE}}}.DataStructures;

/// <inheritdoc cref="Asset{T}"/>
[System.Runtime.CompilerServices.CompilerGenerated]
internal readonly record struct LazyAsset<T> where T : class
{
    private readonly Lazy<Asset<T>> _asset;

    private readonly string _key;

    public readonly Asset<T> Asset => _asset.Value;

    /// <inheritdoc cref="Asset{T}.Value"/>
    public readonly T Value => Asset.Value;

    public readonly bool IsReady => 
        Asset is not null && 
        Value is not null && 
        Asset.IsLoaded &&
        !Asset.IsDisposed;

    public readonly string Key => _key;

    /// <inheritdoc cref="ModContent.Request{T}"/>
    public LazyAsset(string name)
    {
        _key = name;
        _asset = new Lazy<Asset<T>>(() => ModContent.Request<T>(name));
    }

    public void Wait()
    {
        Asset.Wait();
    }

    public static implicit operator Asset<T>(LazyAsset<T> asset)
    {
        return asset.Asset;
    }

    public static implicit operator T(LazyAsset<T> asset)
    {
        return asset.Value;
    }
}
""");

        return new("DataStructures/LazyAsset.g.cs", writer.ToString());
    }

    #endregion
}
