<Project>
	<!-- Include all assets as additional text -->
	<ItemGroup>
		<AdditionalFiles Include="$(MSBuildProjectFileDirectory)Assets\**"/>
	</ItemGroup>

	<ProjectReference Include=".\shader-reader\ShaderDecompiler.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
	<ProjectReference Include=".\AssetGen\AssetGen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
</Project>