<Project>
	<ItemGroup>
		<!-- Include all assets as additional text -->
		<AdditionalFiles Include="$(MSBuildProjectFileDirectory)Assets\**"/>

		<ProjectReference Include="shader-reader\ShaderDecompiler.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
		<ProjectReference Include="AssetGen\AssetGen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer"/>
	</ItemGroup>
</Project>